### ISSUE TITLE
frederick douglass speech

### ISSUE THREAD

**Issue by ahsu11** [crispysodium/asians4blacklives#2]
https://teachingamericanhistory.org/library/document/what-to-the-slave-is-the-fourth-of-july/

basically he (a freed slave) was asked by white abolitionists to give a speech on the 4th of july about independence and such but instead he gave this speech on the july 5th - "I say it with a sad sense of the disparity between us. I am not included within the pale of this glorious anniversary! Your high independence only reveals the immeasurable distance between us. The blessings in which you, this day, rejoice, are not enjoyed in common. — The rich inheritance of justice, liberty, prosperity and independence, bequeathed by your fathers, is shared by you, not by me. The sunlight that brought life and healing to you, has brought stripes and death to me. This Fourth [of] July is yours, not mine. You may rejoice, I must mourn. "

**Comment by crispysodium** [comment]
added to timeline as a featured element.
